version: '3'

services:
  flask_app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db

  mysql_db:
    build:
      context: ./mysql
    environment:
      MYSQL_DATABASE: projet_db
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
