version: '3'

services:

  flask_app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    networks:
      - elk
      - my_net

  mysql_db:
    build:
      context: ./mysql
    environment:
      MYSQL_DATABASE: projet_db
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - elk 
      - my_net  

  elasticsearch-backend:
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk

networks:
  my-net:
    driver: bridge
  elk:
    driver: bridge